# Generated by Django 4.1.7 on 2023-03-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_folloerscount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FolloersCount',
            new_name='FollowersCount',
        ),
    ]
